export const INTL = {
  TITLE: "All markets",
  TAG_ALL: "All",
  ARIA_SEARCH: "Search markets",
  ARIA_FILTERS: "Filters",
  ARIA_BOOKMARKS: "Bookmarks",
  ARIA_SCROLL_LEFT: "Scroll tags left",
  ARIA_SCROLL_RIGHT: "Scroll tags right",
};

import {
  FILTER_CHIP_ACTIVE_CLASS,
  FILTER_CHIP_BASE_CLASS,
  FILTER_CHIP_DEFAULT_CLASS,
} from "@/src/shared/ui/filter-chip";

export const UI = {
  TAG_SKELETON_COUNT: 8,
  TAG_SCROLL_STEP_MIN_PX: 280,
  TAG_SCROLL_STEP_RATIO: 0.75,
  TAG_SCROLL_CONTROL_WIDTH_PX: 96,
  TAG_SCROLL_CONTROL_ICON_OFFSET_PX: 10,
  CHIP_BASE_CLASS: FILTER_CHIP_BASE_CLASS,
  CHIP_ACTIVE_CLASS: FILTER_CHIP_ACTIVE_CLASS,
  CHIP_DEFAULT_CLASS: FILTER_CHIP_DEFAULT_CLASS,
};
